title: "Delaney's Portfolio"
description: "Web Developer & Designer"
theme: jekyll-theme-minimal
url: "https://delaneygarikayi.github.io"  # No trailing slash!

# Only include plugins GitHub Pages supports
plugins: - jekyll-feed
